### ISSUE TITLE
Implement even distribution on particle entry axis.

### ISSUE THREAD

**Issue by harrymaynard** [harrymaynard/harrymaynard.ca#17]
Currently the particle effects have a 50/50 randomized distribution for axis entry generation. However, since the sky entity uses half the screen height, there tends to be a larger amount of particle entities entered from the right side of the canvas.

**Solution:** Sum the width and height, create random number from the sum of axis, then use that number as basis for axis entry.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the generateEntity method to create a more balanced distribution of particle entries based on the sum of width and height, as per the GitHub issue description.

You can review changes in this commit: https://github.com/mnmnk43434/harrymaynard-harrymaynard.ca-17/commit/08e00c614c3b7ca80c7f87e9b2ec715b9e1ed229.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
